# Build the all in windows/.
# Provide windows for the apps.

all:
# Display server and libraries
	make -C ds/

clean:
# Display server and libraries
	-rm ds/server/bin/*.BIN

clean-all:
# Display server and libraries
	-rm ds/server/bin/*.BIN
