
all:

# POSIX-like commands for eloquent people.
	make -C cmds/

# Experiment with cpp.
#	make -C cpp00/

# Experiment with 3D.
# ps: We can create a library using this.
	make -C heavy/

clean-all:
	-rm *.o 

	-rm cmds/*.o 
	-rm cpp00/*.o 
	-rm heavy/*.o 
