# Compile all the loadable kernel modules.
# For now these are not dynlinked modules.
# Created by Fred Nora.

all:
	make -C dungeon/

clean:
	-rm bin/*.BIN

clean-all:

	-rm bin/*.BIN

	-rm dungeon/*.o
	-rm dungeon/*.BIN 

