# Compiling the ring 3 init process
# Created by Fred Nora

all:

	make -C garden/
	make -C gthouse/
	make -C src/

clean:
	-rm src/*.o
	-rm src/bin/*.BIN

clean-all:
	-rm src/*.o
	-rm src/bin/*.BIN

