# Build the all in windows/.
# Provide windows for the apps.

all:
# Display server and libraries
	make -C ds/
#	make -C gram3d/

clean:
# Display server and libraries
	-rm ds/ds00/*.o
	-rm ds/ds00/bin/*.BIN

clean-all:
# Display server and libraries
	-rm ds/ds00/*.o
	-rm ds/ds00/bin/*.BIN

#	-rm gram3d/bin/*.BIN 
