# Build the all in windows/.
# Provide windows for the apps.

all:
# Display server and libraries
	make -C games3d/

clean:
	-rm games3d/demo00/*.o
	-rm games3d/demo00/bin/*.BIN

clean-all:
	-rm games3d/demo00/*.o
	-rm games3d/demo00/bin/*.BIN

