
all:
# Display server and libraries
	make -C comp/

clean:
# Display server and libraries
	-rm comp/comp00/*.o
	-rm comp/comp00/bin/*.BIN

clean-all:
# Display server and libraries
	-rm comp/comp00/*.o
	-rm comp/comp00/bin/*.BIN

