
# Compile extra commands.

all:

	make -C cmp/
#	make -C env/
#	make -C rect/
#	make -C replace/
	make -C showfun/
#	make -C socket1/
	make -C sum/
#	make -C tascii/
#	make -C tcrypt1/
#	make -C tcrypt2/
#	make -C template/
#	make -C tpass/
#	make -C tprintf/
#	make -C tty/
	make -C udptest/
#	make -C unknown/

clean:
	-rm *.o
	-rm bin/*.BIN
clean-all:
	-rm *.o
	-rm bin/*.BIN
	
	

