
all:

# garden - rtl
	make -C garden/

# gthouse - libs
	make -C gthouse/

clean:

# garden - rtl
	-rm -f garden/rtl/obj/*.o

# gthouse - libs
	#-rm -f gthouse/libcpp/obj/*.o
	-rm -f gthouse/libdisp/obj/*.o
	-rm -f gthouse/libgr/obj/*.o
	-rm -f gthouse/libgr3d/obj/*.o
	-rm -f gthouse/libgws/obj/*.o
	-rm -f gthouse/libio01/obj/*.o

