# Build the all in os/.
# This is the Desktop Environment.
# Client-side gui applications and wallpapers.
# Created by Fred Nora.

all:
# Client-side GUI applications
	make -C apps/

clean:
# Client-side GUI applications
	-rm apps/bin/*.BIN

clean-all:
# Client-side GUI applications
	-rm apps/bin/*.BIN

