# Created by Fred Nora

all:
	make -C hunter/
	make -C farmer/

# Some experiments for clever people.
	make -C heavy/
	make -C cpp00/
	make -C netu/

clean:
	-rm -f *.o
	-rm -f bin/*.BIN

clean-all:
	-rm -f *.o
	-rm -f bin/*.BIN

