# Compile all in halls/ folder

all:

# fs
	make -C fs/

# BUSes
	make -C platform/

# Devices (exec, per, req)
	make -C dev/

# Human-Computer Interfce devices
	make -C hcidev/

clean:
# ...
