# Build the all in os/.
# This is the Desktop Environment.
# Client-side gui applications and wallpapers.
# Created by Fred Nora.

all:
# Client-side GUI applications
	make -C shell/

clean:
# Client-side GUI applications
	-rm shell/bin/*.BIN

clean-all:
# Client-side GUI applications
	-rm shell/bin/*.BIN
