# Compile all in kres/ folder

all:
	make -C bus/

# todo
#	make -C cpu/

	make -C dev/blkdev/
	make -C dev/chardev/
	make -C dev/netdev/
	make -C dev/

	make -C fs/
	make -C mm/
	make -C net/
# ...

clean:
# ...
