# Build the all in os/.
# This is the Desktop Environment.
# Client-side gui applications and wallpapers.
# Created by Fred Nora.

all:

# Unix-like commands
#	make -C shell00/
# Client-side GUI applications
	make -C shell01/

#	make -C xapps/

clean:
# Unix-like commands
#	#-rm she00/base/bin/*.BIN
# Client-side GUI applications
	-rm shell01/bin/*.BIN
#	-rm xapps/bin/*.BIN 

clean-all:
# Unix-like commands
#	-#rm shell00/base/bin/*.BIN
# Client-side GUI applications
	-rm shell01/bin/*.BIN
#	-rm xapps/bin/*.BIN 
